### ISSUE TITLE
Проверено!

### ISSUE THREAD

**Issue by rmarsu** [RichCake/calc_api_go#1]
Неплохая работа! Мне понравилось.
Из минусов:
- Не хватает курлов , по условию должны быть курлы на все варианты ошибки
- При получении поврежденного json ответ об ошибке не в json
- Не очень красивые ифы в application

**Comment by RichCake** [comment]
Привет. Спасибо, что написал ишью.

1. Добавил курлы на все случаи жизни в таблицу
2. Не очень понял. Вот поврежденный json и ответ в json:

```
curl --location 'localhost:8080/api/v1/calculate' --header 'Content-Type: application/json' --data '{"expressio: "2++2"}'  
```
```
{"error":"invalid character '2' after object key"}
```

3. Убрал вложенные ифы

**Comment by rmarsu** [comment]
Хорошо , похоже спутала тебя с другим во время проверки , я подняла балл (за исправления , которые ты сделал сейчас - тоже)
